### ISSUE TITLE
Hi sir, i'm a student and have a project similar with your. However i cannot run it because some gem is missing, and i use rails 4

### ISSUE THREAD

**Issue by ThongNH93** [gullitmiranda/gm_temp#1]

**Comment by gullitmiranda** [comment]
This project was discontinued, in fact this repository was just a test run at the time was successful but should have several outdated or missing dependencies.
Particularly I opted not to use the more activeadmin, though he is well lat he brought a very large and unnecessary burden for the project. Currently I prefer to work with the use of the devise and add only the dependencies that are really needed for my project.

**Comment by ThongNH93** [comment]
Thank for your reply sir, so do you have any rails project like this one can run successfully. I very need it as a reference to do my project at university

**Comment by gullitmiranda** [comment]
Project using activeadmin:
- https://github.com/inossidabile/mastering_aa
- https://github.com/leandromoreira/playground.activeadmin

Tutorials:
- http://code.tutsplus.com/tutorials/create-beautiful-administration-interfaces-with-active-admin--net-21729
- http://railscasts.com/episodes/284-active-admin

**Comment by ThongNH93** [comment]
Thank for your help sir, it very helpful with me!!!
